// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxtoiQvuZaEOzAU2YwtEi6SeCVRdQvaU',
    appId: '1:979682598195:web:5231e7019eb60f1d9cb246',
    messagingSenderId: '979682598195',
    projectId: 'instagram-clone-82d7c',
    authDomain: 'instagram-clone-82d7c.firebaseapp.com',
    storageBucket: 'instagram-clone-82d7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEclGSqKq2Z3ucel3wzZCYCgf-259soCo',
    appId: '1:979682598195:android:5fb616e7926168d99cb246',
    messagingSenderId: '979682598195',
    projectId: 'instagram-clone-82d7c',
    storageBucket: 'instagram-clone-82d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNG1M8PRbVPdeNVitU4ZQ2BmlBiAFlPI',
    appId: '1:979682598195:ios:b64113e10e8af1f59cb246',
    messagingSenderId: '979682598195',
    projectId: 'instagram-clone-82d7c',
    storageBucket: 'instagram-clone-82d7c.appspot.com',
    iosBundleId: 'com.example.instagram',
  );
}
